services:
  prometheus:
    image: prom/prometheus:v2.35.0
    network_mode: host
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus-data:/prometheus
    command:
    - '--config.file=/prometheus/prometheus.yaml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
    - 9090:9090
    extra_hosts:
    - "host.docker.internal:192.168.5.2"
    #docker run -it --rm alpine nslookup host.docker.internal

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    network_mode: host
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
    - 3000:3000
    volumes:
    - ./grafana-data:/var/lib/grafana
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_SERVER_DOMAIN=localhost
    - GF_LOG_MODE=console file
    - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug

volumes:
  prometheus-data:
    external: true
  grafana-data:
    external: true



